---
- hosts: nodes

  tasks:
    - name: reboot host
      shell: sleep 10 && /sbin/shutdown -r now
      async: 300
      poll: 0
      become: true

    - name: waiting for server booting up
      local_action: wait_for
      args:
        host: ''
        port: 22
        delay: 30
        timeout: 600
        state: started
      become: false
