---
- hosts: nodes
  remote_user: root
  tasks:
  - name: Baixando as imagens para acelerar a instalação versão
    docker_image:
      name: "{{ item }}"
    with_items:
      #- ose-sti-builder
      - registry.access.redhat.com/openshift3/ose-haproxy-router:{{openshift_image_tag}}
      - registry.access.redhat.com/openshift3/ose-deployer:{{openshift_image_tag}}
      - registry.access.redhat.com/openshift3/ose-pod:{{openshift_image_tag}}
      - registry.access.redhat.com/openshift3/ose-keepalived-ipfailover:{{openshift_image_tag}}
      - registry.access.redhat.com/openshift3/ose-docker-registry:{{openshift_image_tag}}
      - registry.access.redhat.com/openshift3/registry-console:{{openshift_image_tag}}
      - registry.access.redhat.com/openshift3/ose-control-plane:{{openshift_image_tag}}
      - registry.access.redhat.com/rhel7/etcd:3.2.22
