kind: LDAPSyncConfig
apiVersion: v1
url: ldap://sede-rootdc01.vico.corp:389
insecure: true
bindDN: "CN=OpenShift,OU=Contas de Sistemas,DC=vico,DC=corp"
bindPassword:
  file: /etc/origin/master/ldap-sync/ldap.vico.bindPassword.encrypted
  keyFile: /etc/origin/master/ldap-sync/ldap.vico.bindPassword.key
rfc2307:
  groupsQuery:
    baseDN: "OU=Grupos de Segurança,DC=vico,DC=corp"
    scope: sub
    derefAliases: never
    filter: (objectClass=group)
    pageSize: 9999
  groupUIDAttribute: dn
  groupNameAttributes: [ sAMAccountName ] 
  groupMembershipAttributes: [ member ]
  usersQuery:
    baseDN: "dc=vico,dc=corp"
    scope: sub
    derefAliases: never
    pageSize: 9999
  userUIDAttribute: dn
  userNameAttributes: [ sAMAccountName ]
  tolerateMemberNotFoundErrors: false
  tolerateMemberOutOfScopeErrors: false

